"""Create share_diary table

Revision ID: 15acd6952d9a
Revises: 8a52affdb4de
Create Date: 2025-06-08 18:50:22.263737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15acd6952d9a'
down_revision: Union[str, None] = '8a52affdb4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharediary',
    sa.Column('share_diary_id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=2048), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.diary_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_diary_id')
    )
    op.create_index(op.f('ix_sharediary_share_diary_id'), 'sharediary', ['share_diary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharediary_share_diary_id'), table_name='sharediary')
    op.drop_table('sharediary')
    # ### end Alembic commands ###
