"""Add reference_text column to users

Revision ID: 5caf2f02e470
Revises: ebc0915c9bd2
Create Date: 2025-05-29 15:51:11.653883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5caf2f02e470'
down_revision: Union[str, None] = 'ebc0915c9bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reference_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reference_text')
    # ### end Alembic commands ###
