"""Change photo from BLOB to URL string

Revision ID: d8b510650607
Revises: 6e47aa6d1bb5
Create Date: 2025-06-05 03:50:25.229024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b510650607'
down_revision: Union[str, None] = '6e47aa6d1bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'photo',
               existing_type=sa.String(length=2048),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
