"""Create user, diary, and temp_diary tables

Revision ID: ebc0915c9bd2
Revises: a3f1fb1845f7
Create Date: 2025-05-23 15:57:40.049260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc0915c9bd2'
down_revision: Union[str, None] = 'a3f1fb1845f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('diary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('photo', sa.BLOB(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('diary_id')
    )
    op.create_index(op.f('ix_diary_diary_id'), 'diary', ['diary_id'], unique=False)
    op.create_table('temp_diary',
    sa.Column('temp_diary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('temp_diary_id')
    )
    op.create_index(op.f('ix_temp_diary_temp_diary_id'), 'temp_diary', ['temp_diary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_diary_temp_diary_id'), table_name='temp_diary')
    op.drop_table('temp_diary')
    op.drop_index(op.f('ix_diary_diary_id'), table_name='diary')
    op.drop_table('diary')
    # ### end Alembic commands ###
