# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - ms-fom-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      # - name: Check DATABASE_URL
      #   run: echo "DATABASE_URL=${{ env.DATABASE_URL }}"

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52E41C2F564C4FE4890E3703BCE34A5D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2AE45211DDE4168981F8C54883946DC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2635FE1232DB4C0DBF3DE70187B79632 }}

      - name: Set Database URL
        run: |
          az webapp config appsettings set \
            --name ms-fom-backend \
            --resource-group 6th_final_6team \
            --settings DATABASE_URL="${{ secrets.DATABASE_URL }}"

      - name: Set Autogen Env Variables
        run: |
          az webapp config appsettings set \
            --name ms-fom-backend \
            --resource-group 6th_final_6team \
            --settings \
              AUTOGEN_API_KEY="${{ secrets.AUTOGEN_API_KEY }}" \
              AUTOGEN_MODEL_NAME="${{ secrets.AUTOGEN_MODEL_NAME }}" \
              AUTOGEN_API_VERSION="${{ secrets.AUTOGEN_API_VERSION }}" \
              AUTOGEN_AZURE_ENDPOINT="${{ secrets.AUTOGEN_AZURE_ENDPOINT }}"

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "fombackend"
          slot-name: "Production"
